### ISSUE TITLE
CI: Transient 403 Forbidden errors when pushing to ghcr.io

### ISSUE THREAD

**Issue by victorlin** [nextstrain/docker-base#131]
While running the CI workflow multiple times over the past few days, I noticed several instances of 403 errors which happen after the build finishes and the image is being pushed to GitHub Container Registry (GHCR). A few examples ([1](https://github.com/nextstrain/docker-base/actions/runs/4298745862/jobs/7493216187), [2](https://github.com/nextstrain/docker-base/actions/runs/4298745862/jobs/7510704448)):

```
ERROR: failed to push ghcr.io/nextstrain/base-native-builder:branch-98-merge: unexpected status: 403 Forbidden
ERROR: failed to push ghcr.io/nextstrain/base-native-builder:branch-98-merge: failed commit on ref "manifest-sha256:40dee82b1e0a00c8568931433a053fa7049ff66fef862a560ebb23b89a2fdd98": unexpected status: 403 Forbidden
```

These are obviously transient because re-runs are successful. However, the rate at which it happened is a bit concerning - [this run](https://github.com/nextstrain/docker-base/actions/runs/4298745862) only succeeded on the 3rd retry.

This seems to be a [common issue](https://github.com/docker/build-push-action/issues/463) with many suggested solutions/workarounds. Here are the suggestions I've extracted, with notes on why they don't apply here (or already have been applied):

1. [Delete the image/package](https://github.com/docker/build-push-action/issues/463#issuecomment-924868666).
    - This does not apply to us since as we automatically delete the image (and entire package if necessary) at the end of each run.
2. [Select "Inherit access from source repository" on the package](https://github.com/docker/build-push-action/issues/463#issuecomment-926229761).
    - We can't try this since the package is transient.
3. If using `GITHUB_TOKEN`, [switch to using a PAT](https://github.com/docker/build-push-action/issues/463#issuecomment-939394233).
    - This has [already been applied](https://github.com/nextstrain/docker-base/blob/d59452c4800c09e7f418c80d70379523a7cf84ef/.github/workflows/ci.yml#L35-L36) since I encountered similar transient 403 errors in the past, and it seemed to help at first but probably not with more observations.
4. [Select the **Read and write permissions** option for **Workflow permissions** in the Actions' settings page of the repository](https://github.com/docker/build-push-action/issues/463#issuecomment-1125443655).
    - This is already set.
5. [Verify that the PAT includes the `write:packages` scope](https://github.com/docker/build-push-action/issues/463#issuecomment-1298538631).
    - It does.
6. [Prevent the Docker login action from logging out at the end of the job.](https://github.com/docker/build-push-action/issues/463#issuecomment-924300445)
    - This was tried in #149 and it did not fix the issue.

If this keeps happening, it might be worth modifying [delete-from-ghcr.js](https://github.com/nextstrain/docker-base/blob/e70bbf003cf5ae4cbf51958505b82e1e82bff630/devel/delete-from-ghcr.js) to retain the package so suggestion (2) can be attempted.

### Other occurrences

- [2023-03-21T21:15:21.8301039Z](https://github.com/nextstrain/docker-base/actions/runs/4483603931/jobs/7883087313)

**Comment by tsibley** [comment]
> If this keeps happening, it might be worth modifying [delete-from-ghcr.js](https://github.com/nextstrain/docker-base/blob/e70bbf003cf5ae4cbf51958505b82e1e82bff630/devel/delete-from-ghcr.js) to retain the package so suggestion (2) canx`

Looks like this got truncated?

**Comment by victorlin** [comment]
@tsibley oops, not sure what happened there. Fixed.

**Comment by joverlee521** [comment]
Documenting more occurrences of this error that I've seen:
* [2023-03-14T01:19:22.9154104Z](https://github.com/nextstrain/docker-base/actions/runs/4410881635/jobs/7728832173)
* [2023-04-05T23:58:01.5084235Z](https://github.com/nextstrain/docker-base/actions/runs/4622997842/jobs/8176358300)

**Comment by tsibley** [comment]
I wonder if this is dependent on the time it takes the build to run, i.e. the time between the `docker login ghcr.io` and when buildx tries to push. I can imagine the token retrieved at login time being time-limited with an expiry and our build time exceeding that stochastically.

**Comment by tsibley** [comment]
Ahh, nevermind. The token retrieved by `docker login ghcr.io` (i.e. returned by `https://ghcr.io/token`) is just the normal GitHub token used as the password but base64-encoded.

**Comment by corneliusroemer** [comment]
Seems to have happened again recently: 
```
ERROR: failed to solve: failed to push [ghcr.io/nextstrain/base-builder:build-20230525T081004Z](http://ghcr.io/nextstrain/base-builder:build-20230525T081004Z): failed commit on ref “manifest-sha256:3ce4f6c1ad2053d6d722461abba78fd47ff65aa6373f82408768325d89b0ebf1”: unexpected status: 403 Forbidden
```
https://github.com/nextstrain/docker-base/actions/runs/5077615346/jobs/9121104632#step:8:15521

**Comment by victorlin** [comment]
I'm working on #153 in an attempt to fix this. Even though the PR is not merged yet, the effects are already in place since it doesn't delete the last tagged version of each package (thus the package won't be deleted by other runs).

If anyone sees another occurrence of this error, let me know!
