### ISSUE TITLE
cvxopt cannot be imported due to missing lapack shared library

### ISSUE THREAD

**Issue by huddlej** [nextstrain/docker-base#142]
### Current Behavior

When running flu builds with `nextstrain build` and the latest Docker image on my ARM64 Mac, the `augur titers` command fails with a cvxopt error like this:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/cvxopt/__init__.py", line 50, in <module>
    import cvxopt.base
ImportError: liblapack.so.3: cannot open shared object file: No such file or directory
```

### How to reproduce

Steps to reproduce the current behavior:
1. Run `nextstrain shell .`
2. Run `python`
3. Run `import cvxopt`

### Possible solution

Install or fix LAPACK library for Python?

### Your environment: if running Nextstrain locally

 - Operating system: Mac OS Monterey (12.6)
 - Architecture: ARM64, M2 chip
 - CLI version 6.2.0 (standalone)
 - Docker Desktop version 4.12.0 (85629)
 - Docker image: `nextstrain/base:build-20230411T103027Z`

**Comment by tsibley** [comment]
This is reproducible on `blab-mac`.

**Comment by victorlin** [comment]
Assuming this only affects the ARM64 image variant, a temporary workaround might be to run the AMD64 variant under emulation:

```
docker pull --platform linux/amd64 nextstrain/base:build-20230411T103027Z
nextstrain build …
```

**Comment by victorlin** [comment]
This is likely because OpenBLAS/LAPACK are only installed for build, and not included in the final image. It's this way because of how I (mis)interpreted the [installation instructions](https://cvxopt.org/install/#building-and-installing-from-source). I'll into adding them properly.

**Comment by huddlej** [comment]
Thank you both for looking into this, @tsibley and @victorlin!
