### ISSUE TITLE
Remove pangoLEARN

### ISSUE THREAD

**Issue by huddlej** [nextstrain/docker-base#157]
### Context
[PangoLEARN has been deprecated](https://github.com/cov-lineages/pangoLEARN).

### Description
We should remove [PangoLEARN from the image](https://github.com/nextstrain/docker-base/blob/1b0d1998c8cb03cbd0b5eb630fcd86fdfb247c99/Dockerfile#L175-L181), since it is no longer supported.

**Comment by joverlee521** [comment]
There were previous discussions around this in [conda-base](https://github.com/nextstrain/conda-base/issues/7) where the main blocker seems to be the use of the `run_pangolin` flag in ncov. 

I think we should remove support for the `run_pangolin` flag in ncov before we completely remove it from our runtimes.
Although, pangolin/pangoLEARN have already been [removed from conda-base](https://github.com/nextstrain/conda-base/pull/14).
