### ISSUE TITLE
Provide native binaries for all programs on all platforms

### ISSUE THREAD

**Issue by victorlin** [nextstrain/docker-base#162]
### Progress tracker

- [ ] MAFFT
- [ ] IQ-TREE: WIP on branch [victorlin/build-iqtree](https://github.com/nextstrain/docker-base/tree/victorlin/build-iqtree)
- [ ] Nextalign/Nextclade v1
- [ ] tsv-utils
- [ ] gofasta
- [ ] minimap2

### Background

Currently, each of these programs are downloaded using one binary for all both available platforms `amd64` and `arm64`. Since there is more widespread support for emulation of `amd64` binaries on an `arm64` host, the `amd64` binaries are downloaded.

This means that for `arm64` hosts, `amd64` emulation must be used to run these programs. The most common use case is running the Nextstrain Docker runtime on an Apple silicon Mac computer. These computers support the necessary emulation using Rosetta 2, however note that emulation can result in slower run times compared to running with the native binary.

### Potential solutions

In preferred order:

1. Download dynamically based on [TARGET* variables](https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope)
    1. Official binaries
    2. Unofficial binaries
2. Build from source.

**Comment by victorlin** [comment]
This might still be good to do at some point, but things are working fine with the current setup. Closing for now.

**Comment by corneliusroemer** [comment]
conda-forge/bioconda have native linux-aarch64 for all of these:

- mafft
- iqtree
- tsv-utils
- gofasta
