### ISSUE TITLE
Install CVXOPT from PyPI on linux/arm64

### ISSUE THREAD

**Issue by victorlin** [nextstrain/docker-base#187]
Currently, CVXOPT is [built from source](https://github.com/nextstrain/docker-base/blob/27465243aa645e32ad8c134b779a6d3f96622b69/Dockerfile#L284-L314) because there are no pre-built binaries for linux/arm64. The downside is that this is an extensive workaround that is platform-specific.

## Solution

Wait for a CVXOPT release that provides ARM64/AARCH64 Linux binaries on PyPI.

https://github.com/nextstrain/docker-base/labels/blocked on https://github.com/cvxopt/cvxopt/issues/252

> [!NOTE]
> This solution is out of our control, and I think it's fine to keep building from source. The extra build time isn't a problem with caching.

**Comment by victorlin** [comment]
@joverlee521 noted in https://github.com/nextstrain/augur/issues/1328#issue-1948394051 that CVXOPT version 1.3.1 [has macOS arm64 wheels for Python 3.9, 3.10, 3.11](https://github.com/cvxopt/cvxopt/issues/234#issuecomment-1542151285). However, those can't be used for linux/arm64.

**Comment by victorlin** [comment]
This might still be good to do at some point, but things are working fine with the current setup. Closing for now.

**Comment by alezana** [comment]
This is still a very much desired feature to simplify multiarch build in docker :)

**Comment by victorlin** [comment]
@alezana this repo for is a Docker build, not CVXOPT. Do you mean https://github.com/cvxopt/cvxopt/issues/252?

**Comment by victorlin** [comment]
Re-opening because [pre-built wheels are now available](https://github.com/cvxopt/cvxopt/issues/252#issuecomment-2431133625).

**Comment by victorlin** [comment]
In the worst case with a cache miss on the [CVXOPT build](https://github.com/nextstrain/docker-base/blob/301ec7e48dab5381f8152a7dcb2d385f08a78dcd/Dockerfile#L283-L313), that step takes [~13m](https://github.com/nextstrain/docker-base/actions/runs/10835879954):

```
[linux/arm64] WORKDIR /cvxopt                                                                        | CACHED          ▏
[linux/arm64] RUN if [[ "linux/arm64" == linux/arm64 ]]; then       apt-get update && apt-get instal | 778.7s (29.5%)  ███████████████████▋
```

Removing this step is an easy win for (but doesn't directly address) #234.
