### ISSUE TITLE
CI failing: 404 when fetching nodejs_18.17.1-deb-1nodesource1_arm64.deb

### ISSUE THREAD

**Issue by victorlin** [nextstrain/docker-base#188]
The CI build is failing as of yesterday's [run](https://github.com/nextstrain/docker-base/actions/runs/6699980958) for Auspice v2.50.0.

This should go away when ~the [upstream issue](https://github.com/nodesource/distributions/issues/1709) is resolved~ we migrate to use the new installation method.

**Comment by tsibley** [comment]
Seems like the upstream issue may not be resolved given the switch to package management (noted on the issue, but quoting from [official docs](https://github.com/nodesource/distributions#new-update-%EF%B8%8F)):


> We'd like to inform you of important changes to our distribution repository [nodesource/distributions](https://github.com/nodesource/distributions).
> 
> **What's New:**
> 
> - _**Package Changes:** DEB and RPM packages are now available under the `nodistro` codename. We no longer package the installer coupled to specific versions. This means you can install Node.js on almost any distro that meets the minimum requirements._
> - _**Installation Scripts:** The installation scripts `setup_XX.x` are no longer supported and are not needed anymore, as the installation process is straightforward for any RPM and DEB distro._
> - **Questions and concerns:** To resolve questions and discuss concerns about this update we've opened this discussion space [New distribution&#39;s packages](https://github.com/nodesource/distributions/discussions/#123456)
>

**Comment by victorlin** [comment]
Yeah I just read that too. I'll make a PR to use the new installation method.
