### ISSUE TITLE
Install augur/auspice through PyPI/npm

### ISSUE THREAD

**Issue by trvrb** [nextstrain/docker-base#19]
@tsibley ---

Is there any advantage to the current downloading of `release` branch from GitHub (https://github.com/nextstrain/docker-base/blob/master/Dockerfile#L124) and subsequent pip install compared to just running `pip3 install nextstrain-augur` to grab latest release now that we're using PyPI for augur?

And relatedly, what about installing auspice directly through npm in a similar fashion? We're pushing all auspice releases through npm now.

**Comment by jameshadfield** [comment]
@trvrb I raised this with tom earlier this year and, from memory, the reason this is not being done is so that one can overlay a local version of augur/auspice into the docker container when you run `nextstrain`.

**Comment by tsibley** [comment]
James is correct; that's the primary reason. A secondary reason is that it makes it easy for the Dockerfile to be parameterized with a different branch/tag/git ref (although we're not doing this yet, it's been on my mental list from the beginning in order to support more dev builds).

**Comment by tsibley** [comment]
@trvrb I should ask, did this cause issues for you? Is there an advantage to PyPi/npm that we're missing out on?

**Comment by trvrb** [comment]
No reason. I just thought it might streamline the Dockerfile and make it easier to read what's going on. But I'm happy to keep things happening via GitHub.
