### ISSUE TITLE
awscli `--no-sign-request` option not working

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/docker-base#213]
## Context 

I was trying to implement the [conditional use of the `--no-sign-request` flag for the avian flu](https://github.com/nextstrain/avian-flu/pull/49) but was still running into "Unable to locate credentials" error. 

I _think_ this is dependency issue within docker-base as I am able to use the flag successfully in conda-base.

**Comment by joverlee521** [comment]
I thought it might be a bug with the pinned `awscli` v1.18.195, but the awscli changelog shows this [bug was fixed in v1.7.1](https://github.com/aws/aws-cli/blob/b0c4bd942f5e10eaec54433cd6ec118e1dc3dac5/CHANGELOG.rst#L17510). 

The flag works within the Nextstrain shell if I re-install `awscli` with:

```
pip install awscli==1.18.195 --upgrade
...
Installing collected packages: PyYAML, botocore, s3transfer
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yte 1.5.4 requires pyyaml<7.0,>=6.0, but you have pyyaml 5.3.1 which is incompatible.
boto3 1.34.106 requires botocore<1.35.0,>=1.34.106, but you have botocore 1.19.35 which is incompatible.
boto3 1.34.106 requires s3transfer<0.11.0,>=0.10.0, but you have s3transfer 0.3.7 which is incompatible.
aiobotocore 2.13.0 requires botocore<1.34.107,>=1.34.70, but you have botocore 1.19.35 which is incompatible.
Successfully installed PyYAML-5.3.1 botocore-1.19.35 s3transfer-0.3.7
```

There are dependencies updates shown, so it's due to some dependency incompatibility issue?

**Comment by joverlee521** [comment]
Ah, because the Nextstrain CLI is pip installed _after_ the awscli, it updates the botocore dependencies. 

I don't really want to touch the [Nextstrain CLI botocore dependency hell](https://github.com/nextstrain/cli/blob/8ed779c9741da868341ca4518e8eff83ffba8e60/setup.py#L102-L129), so I think the easiest is to upgrade the `awscli`.

**Comment by jameshadfield** [comment]
(Or we could just change avian-flu to use `curl`, right?)

**Comment by joverlee521** [comment]
Flag works as expected after matching botocore v1.34.106 with awscli v1.32.106:

```
pip install awscli==1.32.106 --upgrade 
Collecting awscli==1.32.106
  Downloading awscli-1.32.106-py3-none-any.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 39.4 MB/s eta 0:00:00
Requirement already satisfied: rsa<4.8,>=3.1.2 in /usr/local/lib/python3.10/site-packages (from awscli==1.32.106) (4.5)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /usr/local/lib/python3.10/site-packages (from awscli==1.32.106) (0.10.1)
Requirement already satisfied: colorama<0.4.7,>=0.2.5 in /usr/local/lib/python3.10/site-packages (from awscli==1.32.106) (0.4.3)
Requirement already satisfied: docutils<0.17,>=0.10 in /usr/local/lib/python3.10/site-packages (from awscli==1.32.106) (0.15.2)
Requirement already satisfied: botocore==1.34.106 in /usr/local/lib/python3.10/site-packages (from awscli==1.32.106) (1.34.106)
Requirement already satisfied: PyYAML<6.1,>=3.10 in /usr/local/lib/python3.10/site-packages (from awscli==1.32.106) (6.0.1)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.10/site-packages (from botocore==1.34.106->awscli==1.32.106) (1.26.18)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.10/site-packages (from botocore==1.34.106->awscli==1.32.106) (2.9.0.post0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.10/site-packages (from botocore==1.34.106->awscli==1.32.106) (0.10.0)
Requirement already satisfied: pyasn1>=0.1.3 in /usr/local/lib/python3.10/site-packages (from rsa<4.8,>=3.1.2->awscli==1.32.106) (0.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.34.106->awscli==1.32.106) (1.16.0)
Installing collected packages: awscli
Successfully installed awscli-1.32.106
```

---

I don't think it's sustainable to have to maintain the compatibility of awscli with the dependencies of the Nextstrain CLI. 
Any reason we can't use `pipx` to install packages in docker-base?

**Comment by tsibley** [comment]
We could also install the standalone Nextstrain CLI instead of the PyPI package.

**Comment by tsibley** [comment]
Or could also install AWS CLI v2, which is not installed via Pip. Or yes, could use Pipx, but that'll require some additional configuration.

**Comment by joverlee521** [comment]
> Or could also install AWS CLI v2, which is not installed via Pip. 

Ah, yeah. Conda-base includes AWS CLI v2 so we could match it here.

**Comment by joverlee521** [comment]
Hrm, [seeing an error](https://github.com/nextstrain/docker-base/actions/runs/9375679769/job/25814223283#step:9:41343) for my attempt to switch to AWS CLI v2 in https://github.com/nextstrain/docker-base/commit/ffdac83edcf27a8125a2255b470185e896b4d47d. 

> #138 ERROR: failed to calculate checksum of ref u75h8s8905a7n3r90cq32i1t3::8cv66vaxj2qiznjawq63ih86d: "/usr/local/bin/aws": not found

I must be doing something wrong with https://github.com/nextstrain/docker-base/blob/ffdac83edcf27a8125a2255b470185e896b4d47d/Dockerfile#L224-L227

Will investigate tomorrow.

**Comment by tsibley** [comment]
> Or yes, could use Pipx, but that'll require some additional configuration.

The least change option for now might be installing awscli v1 from PyPI with pip (no change) but doing so into an isolated venv. This requires ~no additional configuration like `pipx` and doesn't have the extra baggage/changes of `pipx`.
