### ISSUE TITLE
Add IQtree version with cmaple feature

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/docker-base#226]
### Context
I've enabled the cmaple feature in bioconda's iqtree build.

Now what's stopping us from using it in nextstrain builds that are run in ci is lack of that feature in docker-base iqtree.

Binaries are available here: https://github.com/iqtree/iqtree2/releases/tag/v2.3.5.cmaple

Or one could just repackage the bioconda binaries directly - which would have the advantage of `linux-aarch64` being available as well. This would solve #212

**Comment by corneliusroemer** [comment]
As I've mentioned in our Nextstrain zoom call: docker-base is what's holding us back from using iqtree's cmaple mode in workflows with CI. Cmaple mode means we get: a) better trees, b) faster, c) don't need to run a somewhat buggy fix-tree script.

Pinging a few who could be interested/helping here: @huddlej @victorlin @tsibley

**Comment by tsibley** [comment]
The change required here seems trivial? Trying it out in #228.

(Separately, `iqtree2` calling the option that enables CMAPLE `--pathogen` is kinda weird, yeah?)

**Comment by tsibley** [comment]
#228 seems ok to me.
