### ISSUE TITLE
nextstrain docker image need update

### ISSUE THREAD

**Issue by xkxxfyf** [nextstrain/docker-base#24]
the augur version and the Treetime version of nexstrain:latest is 6.2.0 and 0.6.4 ,but new data of this week need Treetime 0.7.4

**Comment by tsibley** [comment]
@huddlej is currently working on releasing Augur 7.0.0 which will include the fixes to Augur and the TreeTime version bump. Once that's released, a new image will build and publish automatically, so I'm going to close this out.

**Comment by xkxxfyf** [comment]
thanks!
