### ISSUE TITLE
Install both iqtree and iqtree2

### ISSUE THREAD

**Issue by trvrb** [nextstrain/docker-base#27]
**Context**  

Currently the Dockerfile installs just IQ-TREE 2 and renames the `iqtree2` binary to `iqtree` to be compatible with Augur (https://github.com/nextstrain/docker-base/blob/master/Dockerfile#L56). However, once Augur https://github.com/nextstrain/augur/issues/636 is resolved, we can instead preferentially launch `iqtree2`.

**Description**   

Suggest to install both `iqtree` and `iqtree2` into the Docker image. But this requires https://github.com/nextstrain/augur/issues/636 to be resolved before this can happen.

**Comment by tsibley** [comment]
I think the original suggestion here (discussed in Slack too at some point, I think) was to have both IQ-TREE v1 and v2 in the image as `iqtree` and `iqtree2`. However, at this point, almost 18 months after the change of `iqtree` from v1 to v2, I think it could be unwise to revert `iqtree` back to v1 in the image. There may very well be uses of `iqtree` that expect v2 at this point, though I don't know if the interfaces of v1 and v2 are very different or not.

What we could do is have v2 as both `iqtree` and `iqtree2` for maximum "just run it"-ness or something… but I'm not sure that's terribly useful either?

**Comment by tsibley** [comment]
On subsequent thought, I'll close this now per the above and we can re-open if folks think there's something useful to do still.
