### ISSUE TITLE
Add Pangolin tools

### ISSUE THREAD

**Issue by huddlej** [nextstrain/docker-base#33]
## Context
[We recently added support for reannotating Pangolin lineages as part of the ncov workflow](https://github.com/nextstrain/ncov/pull/593/files). To support these annotations, we needed to install `pangolin=2.3.8` and `pango-learn=2021.04.01` in the Snakemake Conda environment.

In a previous Nextstrain meeting, we discussed whether to include Pangolin tools in this base image or not given that these tools only work for the ncov workflow and are not needed for any other workflow that uses the "base" image. The consensus at the time was to install Pangolin tools in the base image to make maintenance easier and avoid supporting yet another image that is specific to the ncov workflow.

## Description

To support Pangolin annotations from the ncov workflow, we need to [install pangolin and pango-learn](https://cov-lineages.org/resources/pangolin/installation.html). The creators of Pangolin recommend installation with Conda, but we do not currently support Conda in the Docker image, so we need to install Pangolin and its dependencies manually based on the contents of [the most recent Conda environment file](https://github.com/cov-lineages/pangolin/blob/master/environment.yml).

## Testing

If the software is installed properly, we should be able to run an ncov workflow with `run_pangolin: true` in a `builds.yaml` configuration.

**Comment by huddlej** [comment]
If we do decide we are ok with:

1. installing pathogen-specific tools in the base image
2. installing tools from Conda in the base image

Then we could follow the pattern used in [Snakemake's Dockerfile](https://github.com/snakemake/snakemake/blob/main/Dockerfile), as an example. This approach would need to keep Conda installed in the final image, so the image would be a bit bigger than it is now. On the plus side, I think this inclusion of Conda in the base image would allow users to run their Snakemake workflows with `--use-conda` (as attempted in #32).

**Comment by tsibley** [comment]
Snakemake's approach for activating a default Conda env in the image using `.bashrc` will probably not work for us because we don't execute everything through bash in "interactive" mode. The setting of `PATH` will get most of the way there, but not fully-support all Conda packages as some require setting additional env vars (e.g. to shared library paths) which only happens via `conda activate …`.

**Comment by tsibley** [comment]
On the other hand, Pangolin looks readily installable as a set of Python packages not via Conda, so that would seem to be simpler to me.

**Comment by huddlej** [comment]
Assigning @sidneymbell as an indication that her team at CZI has volunteered to work on this in an upcoming sprint.
