### ISSUE TITLE
Maybe consider splitting augur and auspice

### ISSUE THREAD

**Issue by trvrb** [nextstrain/docker-base#4]
Previously I used Docker compose to split augur and auspice, like so:

https://github.com/blab/nextflu/commit/4f993609f60ef8a73548cd9bb919fb350f887851 (look at `docker/docker-compose.yml`)

This allows a separate augur and auspice containers. Each could be built automatically from the augur and auspice GitHub repos as automated builds on Docker hub and then combined with Docker Compose.

This would make it easier to rebuild images at appropriate times.

**Comment by trvrb** [comment]
AWS Batch doesn't work well with Docker Compose. Much easier to have a single container. We should keep this as a single image if at all possible.

**Comment by tsibley** [comment]
Yes, a single image is much preferred for many reasons.
