### ISSUE TITLE
Nextstrain CLI is pinned at version that's 2 years old

### ISSUE THREAD

**Issue by tsibley** [nextstrain/docker-base#52]
### Current Behavior
https://github.com/nextstrain/docker-base/blob/163cba5590d615d089c0c881077eb5033a9929e0/Dockerfile#L65-L66

### Expected behavior
Nextstrain CLI inside the image is kept up-to-date similar to Augur, Auspice, etc.

At the very least, bump the pin to a more recent version.

**Comment by huddlej** [comment]
Should the exact same approach for installing Augur ([download repo](https://github.com/nextstrain/docker-base/blob/6d656277ebe190bc9070aecbfd2e16b8d4bd7d6d/Dockerfile#L87) and then [pip install](https://github.com/nextstrain/docker-base/blob/6d656277ebe190bc9070aecbfd2e16b8d4bd7d6d/Dockerfile#L98) from there) work as expected?

**Comment by tsibley** [comment]
I would skip the downloading the repo step and just `pip install`. The reason the image uses editable installs from the source repo of Augur and Auspice is so they can be [overlayed at runtime via Nextstrain CLI options](https://docs.nextstrain.org/projects/cli/en/stable/commands/build/#development%20options%20for%20--docker). Overlaying is ostensibly for development/testing work, though I'm not sure it's ever used in practice much.

**Comment by corneliusroemer** [comment]
Just noticed the same when reviewing the docker file.

Should we just unpin? It should just work... I'll make a PR

**Comment by tsibley** [comment]
> Should we just unpin? It should just work... I'll make a PR

Yeah, _should_ be fine, but I'd wanted to first review the backwards incompatible changes between 2.0.0.post1 and the latest version and think thru if they'd break any likely uses of `nextstrain` inside the image (mostly expected to be `deploy` and `remote` commands, which [a quick search of public code](https://cs.github.com/?scopeName=All+repos&scope=&q=%28path%3A**%2FSnakefile+OR+path%3A*.smk+OR+path%3A*.wdl%29+%2Fnextstrain%5Cs%2B%28build%7Cview%7Cdeploy%7Cremote%7Cshell%7Cupdate%7Ccheck-setup%7Clogin%7Clogout%7Cwhoami%7Cversion%29%2F) suggests is true). I just did that now briefly and there's nothing that stands out. So I think unpinning is fine.
