### ISSUE TITLE
Use better caching options to reduce build times

### ISSUE THREAD

**Issue by victorlin** [nextstrain/docker-base#57]
> Switching to buildx should also allow us to use better caching options to reduce build times

_Originally posted by @tsibley in https://github.com/nextstrain/docker-base/issues/49#issuecomment-1159270328_

- [x] Add `--cache-from` for the `branch-*` tag when applicable: ([done](https://github.com/nextstrain/docker-base/pull/88))
- [x] Allow more layers to use caching by placing them before `ARG CACHE_DATE` done: f7fbd3ea75077479d82a8367dd80599ae772d716, a7159ec92fdec26b208e86005004889a511231be

**Comment by victorlin** [comment]
> add `--cache-from` for the `branch-*` tag when applicable

This should be as simple as 649502c8db4c6798a100160995f59118b35594c4. However, I don't think any `--cache-from` is as beneficial as one might expect, since most of the build does not use caching due to the current placement of lines respect to `ARG CACHE_DATE`:

https://github.com/nextstrain/docker-base/blob/b82024bffa7338e40f0804c61822c94213dbd9c9/Dockerfile#L76-L78

Most of this is unavoidable because we don't want to use caching for anything that isn't explicitly pinned to a version, e.g.

https://github.com/nextstrain/docker-base/blob/b82024bffa7338e40f0804c61822c94213dbd9c9/Dockerfile#L87

Though there are version pins that are currently below `ARG CACHE_DATE` which can be moved to above, e.g.

https://github.com/nextstrain/docker-base/blob/b82024bffa7338e40f0804c61822c94213dbd9c9/Dockerfile#L107

**Comment by victorlin** [comment]
While testing #88 locally, I noticed another place for cache improvement.

With the multi-stage build in the Dockerfile, it was pretty obvious that `RUN apt-get update ...` on the builder stage was running when it should be cached. I did some digging and found that this is because of default behavior with `--cache-to`:

From ([buildkit doc](https://github.com/moby/buildkit#export-cache)):

> the inline cache exporter only supports `min` cache mode 

From [buildx build doc](https://docs.docker.com/engine/reference/commandline/buildx_build/#cache-to):

> `mode` - Specifies how many layers are exported with the cache. `min` on only exports layers already in the final build stage, `max` exports layers for all stages. Metadata is always exported for the whole build.

This means the entire builder stage is not cached! `type=inline` should be changed to something else that supports `mode=max`.

**Comment by tsibley** [comment]
Ah! Hmm. I've read those snippets of doc before, but I interpreted "final build stage" as the endpoint (`--target`) of a particular build, but I guess that's not what it means.

**Comment by victorlin** [comment]
@tsibley Oh, you're probably right. On a fresh environment I can confirm that the `RUN apt-get update ...` (and everything else before `ARG CACHE_DATE`) in the builder stage is a cache hit. I'm guessing a Dockerfile edit caused the cache miss earlier.

Now I'm curious how caching behaves on that command. Looking at the output of `docker history nextstrain/base-builder:build-20221005T235113Z`, I see:

```
<missing>      5 days ago   RUN /bin/bash -c apt-get update && apt-get i…   370MB     buildkit.dockerfile.v0
```

If this is cached, shouldn't the layer have been created much earlier? Precisely, [5 months ago](https://github.com/nextstrain/docker-base/blame/master/Dockerfile#L14-L26) based on the blame.

**Comment by tsibley** [comment]
Well, I wouldn't really expect a strong correlation between git commit timing and the layer cache. A cache is by definition ephemeral and optional and if for any reason the cache wasn't used by a subsequent build, then the layer would be recreated and thus younger.
