### ISSUE TITLE
DOC: Do we really build on top of Alpine as mentioned on dockerhub?

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/docker-base#67]
On Dockerhub, we mention that we build on top of alpine. However, I think we use Debian now.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/25161793/177388033-fd650738-c7cc-4ecd-9c68-6a0a9a2288f4.png">

https://hub.docker.com/r/nextstrain/base/

**Comment by tsibley** [comment]
Ah, that's an old copy of the README in this repo. I've updated the readme on Docker Hub to be brief and less prone to falling out of date:

> The base image for Nextstrain's Docker runtime, used primarily by the [Nextstrain CLI](https://docs.nextstrain.org/projects/cli/). For more information about this image, please see the [README](https://github.com/nextstrain/docker-base#readme) for the [image source repository](https://github.com/nextstrain/docker-base).
