### ISSUE TITLE
CI: Distinguish build/test/push phases

### ISSUE THREAD

**Issue by victorlin** [nextstrain/docker-base#69]
*Motivated by https://github.com/nextstrain/docker-base/pull/63#pullrequestreview-1029296674.*

It would be good to clean up the increasingly complex `run` job in the CI workflow. Should also consider #68 here, since that would split the push phase to push `branch-…` before test phase, and push `latest` only after successful test.

**Comment by victorlin** [comment]
The current `run` job can be split into 4 jobs:

1. build
2. push-branch
3. test
4. push-build

I've sketched it out in #101. [The workflow run page](https://github.com/nextstrain/docker-base/actions/runs/3276080393) has a nice visual showing the flow of execution.

Unfortunately, sharing the Docker images between jobs using workflow artifacts is quite inefficient given the large image sizes. Benchmarks from the example workflow run:

- build: ~3 minutes to `docker save` the images to a file
- build: ~13 minutes to upload the file as an artifact
- other jobs: ~3 minutes to download + `docker load` the images

Having separate jobs allows the current pre-test push of `branch-` tags to run in parallel with testing, which is an improvement. However, testing only takes ~1 minute so the overall change is a net increase in time (3 + 13 + 3 - 1 = +18 minutes).

**Comment by victorlin** [comment]
I'm playing with a new idea – pushing to GitHub's Container registry as an intermediate. It's still a [work in progress](https://github.com/nextstrain/docker-base/tree/victorlin/split-ci-with-registry), but the run time does look to be much more reasonable than workflow artifacts.

**Comment by tsibley** [comment]
> I'm playing with a new idea – pushing to GitHub's Container registry as an intermediate.

Ah, nice. I've been thinking for future images (buildpack stuff) we'd want to start pushing only to ghcr.io to consolidate services, with the idea to dual publish nextstrain/base there too.
